name: Build and Release SkillSync

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    tags:
      - 'v*'  # Trigger when a tag like v1.0.0 is pushed

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet flet-cli pyinstaller

      - name: Build SkillSync
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            flet pack main.py --name "SkillSync" --add-data "data:data"
            zip -r SkillSync-mac.zip dist/SkillSync.app
          else
            flet pack main.py --name "SkillSync" --add-data "data;data"
            Compress-Archive -Path dist/SkillSync.exe -DestinationPath SkillSync-win.zip
          fi
        shell: bash

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-SkillSync
          path: |
            SkillSync-mac.zip
            SkillSync-win.zip
          if-no-files-found: ignore

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
