name: Build SkillSync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build SkillSync App
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet flet-cli flet-desktop pyinstaller

      - name: Build app
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            flet pack main.py --name "SkillSync" --add-data "data:data"
            cd dist
            zip -r SkillSync-mac.zip SkillSync.app
          else
            pyinstaller --noconfirm --onefile --windowed --name "SkillSync" main.py --add-data "data;data"
            cd dist
            powershell Compress-Archive -Path SkillSync.exe -DestinationPath SkillSync-win.zip
          fi

      - name: Upload macOS Build
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: SkillSync-mac
          path: dist/SkillSync-mac.zip

      - name: Upload Windows Build
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: SkillSync-win
          path: dist/SkillSync-win.zip
